version: "3"

services:
  server:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=998
      - USER_GID=100
    restart: always
    volumes:
      - /home/Docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000" #UI
      - "2234:22"

# version: "3"

# networks:
#   gitea:
#     external: false

# services:
#   server:
#     image: gitea/gitea:1.14.2
#     container_name: gitea
#     environment:
#       - USER_UID=998
#       - USER_GID=100
#       - GITEA__database__DB_TYPE=mysql
#       - GITEA__database__HOST=db:3306
#       - GITEA__database__NAME=gitea
#       - GITEA__database__USER=gitea
#       - GITEA__database__PASSWD=gitea
#     restart: always
#     networks:
#       - gitea
#     volumes:
#       - /home/Docker/gitea/data:/data
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     ports:
#       - "3000:3000"
#       - "2234:22"
#     depends_on:
#       - db
 
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=gitea
#       - MYSQL_USER=gitea
#       - MYSQL_PASSWORD=gitea
#       - MYSQL_DATABASE=gitea
#     networks:
#       - gitea
#     volumes:
#       - /home/Docker/gitea/mysql:/var/lib/mysql
